package com.hexastyle.simulatorgui;

/**
 * Created by Hexastyle on 1/31/17.
 */
public class ProtocolConstants {
    public static final int END = -1;

    enum PC2A {
        MENU, SCHEMATIC, DIFF_SCHEMATIC, BREADBOARD, DIFF_BREADBOARD, DEVICE_VIEWERS, REMOTE_MOUSE_EVENT, MOUSE_LEFT_PRESSED, MOUSE_MIDDLE_PRESSED,
        MOUSE_RIGHT_PRESSED, MOUSE_RELEASED, MOUSE_MOVED, MOUSE_DRAGGED, REMOTE_BUTTON_EVENT,
        UNDO, REDO, RUN, EDIT, CANCEL, LEFT, RIGHT, DEL, CLONE, LOCK, UNLOCK, HORIZONTAL, VERTICAL, ROTATE, ADD,
    }

    enum A2PC {
        MENU, SCHEMATIC, DIFF_SCHEMATIC, BREADBOARD, DIFF_BREADBOARD, DEVICE_VIEWERS, SYMBOL_TYPE, PATH_LINE, PATH_ARC, PATH_RECT,
        PATH_ROUND_RECT, PATH_CIRCLE, PATH_CHAR, MIN_NUMBER_OF_IOS, MAX_NUMBER_OF_IOS, WIRE_INSTANCE, BB_WIRE_INSTANCE, DEVICE_VIEWER_INSTANCE, ANNOTATION_INSTANCE, INSTANCE_WITH_TYPE,
        COLOR_IO, COLOR_PART, STRING_PART, GRAPH_PART, DELETE, CURSOR, BB_RESISTOR_INSTANCE, BB_LED_INSTANCE, BB_RESISTOR_LED_INSTANCE,
        PATH_POLYGON, DEVICE_GROUP_MENU, LAST_A2PC,
    }

    enum SymbolType {
        ANSI, IEC, DIN
    }

}
